module.exports = {
    AwsResource: require('./aws/AwsResource'),
    Bucket: require('./aws/Bucket'),
    Cognito: require('./aws/Cognito'),
    DnsRecord: require('./aws/DnsRecord'),
    Folder: require('./aws/Folder'),
    IAM: require('./aws/IAM'),
    IdentityPool: require('./aws/IdentityPool'),
    Instance: require('./aws/Instance'),
    Lambda: require('./aws/Lambda'),
    LambdaFunction: require('./aws/LambdaFunction'),
    ObjectInS3: require('./aws/ObjectInS3'),
    Policy: require('./aws/Policy'),
    ReceiptRule: require('./aws/ReceiptRule'),
    ReceiptRuleSet: require('./aws/ReceiptRuleSet'),
    Role: require('./aws/Role'),
    Route53: require('./aws/Route53'),
    S3: require('./aws/S3'),
    SES: require('./aws/SES'),
    Tools: require('./aws/Tools'),
    Util: require('./aws/Util'),
}